### ISSUE TITLE
Pip error installing dependencies

### ISSUE THREAD

**Issue by wouterwln** [Metta-AI/metta#21]
Hi, thanks for the interesting environment design and the implementation. I really think this type of environment allows research towards new techniques in AI research. 

When trying out your environment, I ran into some installation issues. I have a clean clone of the base repository (at commit https://github.com/Metta-AI/metta/commit/9731370f87e108f4187aa14c4038a739c137f761) and am running the installation instructions from the `README.md` ([here](https://github.com/Metta-AI/metta?tab=readme-ov-file#installation)). This triggers a pip error for me that probably has to do with some dependency mismatch issue (`ERROR: Could not find a version that satisfies the requirement sample_factory>=2.1.2`). Is there some alternative way in which I can install the environment? Once again, thanks for the work, and I hope I will be able to come up with an interesting model for the environment!

**Comment by daveey** [comment]
Try removing that requirement. You don't really need samplefactory for what you are doing.

Also, consider installing just the mettagrid environment from https://github.com/Metta-AI/mettagrid rather than pulling the entire metta codebase. You don't need any of the training code.

**Comment by bvdmitri** [comment]
I managed to install the dependencies and run the `./devops/setup_build.sh` script (and downloaded the model) when changing the `sample_factory` requirement from `2.1.2` to `2.1.1`. But the command 
```bash
python -m tools.run cmd=evaluate experiment=baseline.v0.5.4
```
returns 
```
/opt/homebrew/anaconda3/envs/metta/bin/python: No module named tools.run
```
Executing `./devops/run.sh` returns similar error:
```
/opt/homebrew/anaconda3/envs/metta/bin/python: No module named tools
```
Executing scripts directly from the `tools` folder doesn't really work either
```
→ python tools/eval.py
Traceback (most recent call last):
  File "/private/tmp/attempt2/metta/tools/eval.py", line 6, in <module>
    from agent.policy_store import PolicyStore
ModuleNotFoundError: No module named 'agent'
(metta)

→ python tools/play.py
Traceback (most recent call last):
  File "/private/tmp/attempt2/metta/tools/play.py", line 7, in <module>
    from rl.pufferlib.play import play
ModuleNotFoundError: No module named 'rl'
(metta)
```
Somewhere in the process of experimentation I managed to run the `tools/eval.py` but it requested the `run` command line argument but I haven't managed to make it execute with further attempts

**Comment by treeform** [comment]
Hey I think we figured it out with this new commit: https://github.com/Metta-AI/metta/pull/28
Please pull the most recent version and re-run:

```
conda create -n metta python=3.11.7
conda activate metta
pip install -r requirements.txt
./devops/setup_build.sh
```

To set this up. Then this to do the training:

```
python -m tools.train run=my_experiment hardware=macbook
```

If you are still having issues feel free to add me on discord: @treeform and I can debug the setup issues with you in real time.

**Comment by wouterwln** [comment]
Thanks for the update @treeform !! The script indeed now runs! Thanks for the help.
